# Generated by Django 5.1.6 on 2025-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_alter_advertisement_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.TextField(
                choices=[
                    ("OPEN", "Открыто"),
                    ("CLOSED", "Закрыто"),
                    ("DRAFT", "Черновик"),
                ],
                default="OPEN",
            ),
        ),
    ]
